from setuptools import setup

setup(
    name='nirdizati_light',
    version='0.1',
    packages=['src',
              'src.log',
              'src.encoding',
              'src.labeling',
              'src.evaluation',
              'src.explanation',
              'src.explanation.wrappers',
              'src.explanation.confusion_matrix_feedback',
              'src.predictive_model',
              'src.hyperparameter_optimisation'],
    install_requires=[
        'pymining',
        'logging',
        'pandas',
        'pm4py',
        'functools',
        'sklearn',
        'shap',
        'numpy',
        'enum',
        'hyperopt',
        'pathlib',
        'tensorflow'
    ]
)
